drop table if exists board CASCADE;
create table post
(
    id bigint generated by default as identity,
    title varchar(255),
    writer varchar(255),
    body varchar(255),
    favorite integer,
    unlike Integer,
    created_at timestamp,
    updated_at timestamp,
    primary key(id)
);